### ISSUE TITLE
Unable to use widget on https sites

### ISSUE THREAD

**Issue by Nebthtet** [RestingCoder/discord-widget#41]
Just like title says. Installed a security certificate and widget ceased to show. I had to return to (IMHO ugly looking) default one :(

**Comment by tattwamasi** [comment]
It works fine on my site with https.  Have any more information, error messages, etc.?

**Comment by Nebthtet** [comment]
Unfortunately none were displayed. Tested that with normal embed and iframe
version. And I'd really love if I managed to make it work again because the
widget looks awesome.



--
Pozdrawiam / Kind regards,
Maria Czaja

2017-03-28 6:07 GMT+02:00 tattwamasi <notifications@github.com>:

**Comment by tattwamasi** [comment]
Maybe this brings to mind something for the dev, but if it were me trying to help (which I am), I'd need more info.  There's more you can provide.

Browsers tried?  Platforms?  Got a site address other people can see so we can actually see the issue ourselves?  Did you look at the dev console / error console most browsers have the option to display?  Errors typically show a lot more info there even if nothing shows in the normal browser window.

My off the cuff bet is you've hit a cross realm protection feature of the browser.

You can look at https://www.farsight-guild.com to see it working, and view source to see the actual embed.  Note the html is … challenged… looking in terms of indentation, etc. due to it being generated from a static site generator template I'm still working on.

Good luck.  With more info I and others can attempt to help more.

**Comment by RestingCoder** [comment]
Thank you, @tattwamasi 

@Nebthtet please provide the URL for the site so I can reproduce this.

**Comment by Nebthtet** [comment]
Hey @tattwamasi and @RestingCoder - thanks for your replies! Sorry for late response but RL got in the way. Did some more digging as you suggested and it seems that the source of a problem is that code from the widget is perceived as insecure resulting in mixed code error.
You can check out one instance at https://aterdracon.net. I don't know how to avoid mixed code there (and on @tattwamasi 's site there's no problem with that, so I'd be really grateful for any advice as I've never dabbled too much with that and got security certificate recently :))

> Mixed Content: The page at 'https://aterdracon.net/' was loaded over HTTPS, but requested an insecure resource 'http://discordi.deliriousdrunkards.com/render?id=123503253391540225&title=G…ada&theme=dark&join=true&abc=false&showall=true&toggle=false&shownick=true'. This request has been blocked; the content must be served over HTTPS.

I've tested Chrome, Opera, Edge, Firefox and IE11 - all on Win10. I can manually load blocked content resulting in "site is not secure" message.

**Comment by tattwamasi** [comment]
I didn't realize you were using the iframe version.  I do see what you mean now…

So the explanation is right there in the message.  You shouldn't mix non-secure content inside secure content.  You are using the iframe version of the widget with a http source url.  I looked to see if it was available via https and it seems not, but if you can use the embed approach instead of an iframe, it is available via https through the CDN.  You can see from my page or from the examples in his docs how to do that.

@RestingCoder may have an alternate url to serve the iframe from that supports https as another easy alternative.

**Comment by Nebthtet** [comment]
Seem that way will work (awesome!). Is there any way to force the embed to specific size AND have it scrollable (like the iframe)? If I set size using div style parameters there's no scroll bar.

**Comment by tattwamasi** [comment]
Sure, but it's on you at that point to style things the way you want in your css or style properties.  Check the overflow style property.  Google div CSS overflow.  It's what I have to do everytime I want to figure something out 😜.  I'm not a CSS guy.

**Comment by RestingCoder** [comment]
Yeah, unfortunately, the iframe version won't work on a https site. I could add https support some time in the future, but I don't plan on it currently.

You can change literally anything about the way the embed version looks using custom CSS.

Thanks again, @tattwamasi !
